name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

# # Workflow name
# name: Build Prod
# on:
#   push:
#     branches:
#       - master
# # Where will they run
# jobs:
#   build:
#     name: Build app
#     runs-on: ubuntu-latest
#     steps:
#       ## Checkout our repository ###
#       - name: Checkout
#         uses: actions/checkout@v2.3.3


#       - name: Set up our JDK environment
#         uses: actions/setup-java@v1.4.3
#         with:
#           java-version: 17

#       ## Install Android Build Tools ##
#       - name: Set up Android SDK
#         uses: android-actions/setup-android@v2
#         with:
#           api-level: 35
#           build-tools: "35.0.0"
#           target: "android-35"
          
#       ## Build all our Build Types at once ##
#       - name: Build all artifacts
#         id: buildAllApks
#         uses: eskatos/gradle-command-action@v1.3.3
#         with:
#           gradle-version: current
#           wrapper-cache-enabled: true
#           dependencies-cache-enabled: true
#           configuration-cache-enabled: true
#           arguments: assembleProductRelease
          
#       - uses: r0adkll/sign-android-release@v1
#         name: Sign app APK
#         # ID used to access action output
#         id: sign_app
#         with:
#           releaseDirectory: app/build/outputs/apk/product/release
#           signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#           alias: ${{ secrets.ANDROID_ALIAS }}
#           keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#           keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
